### PR TITLE
Fix some PHPStan errors

### LINKED ISSUE #9: Fixing all PHPStan problems
We need dev-master from PHPStan and https://github.com/nunomaduro/larastan/pull/946

```diff
diff --git a/composer.json b/composer.json
index 6c0e997..3e62416 100644
--- a/composer.json
+++ b/composer.json
@@ -29,9 +29,10 @@
     },
     "require-dev": {
         "orchestra/testbench": "^6.9",
-        "nunomaduro/larastan": "^0.6.10",
+        "nunomaduro/larastan": "dev-master",
         "pestphp/pest": "^1.2",
-        "pestphp/pest-plugin-laravel": "^1.0"
+        "pestphp/pest-plugin-laravel": "^1.0",
+        "phpstan/phpstan": "dev-master as 0.12.90"
     },
     "extra": {
         "laravel": {
diff --git a/phpstan.neon b/phpstan.neon
index f586106..a04c137 100644
--- a/phpstan.neon
+++ b/phpstan.neon
@@ -10,11 +10,9 @@ parameters:
     universalObjectCratesClasses:
         - Illuminate\Routing\Route
         - ArchTech\SEO\SEOManager
+    checkMissingIterableValueType: false

     ignoreErrors:
-        - '#SEOManager\|array\|string\|null#'
-        - '#string\|false given#'
-        - '#flipp\(\) should return#'
-        - '#\_\_set\(\) has no return typehint specified#'
-
-    checkMissingIterableValueType: false
+        # Waiting for https://github.com/phpstan/phpstan/issues/5706
+        - '#^Cannot call method (flipp|get|set)\(\) on ArchTech\\SEO\\SEOManager\|array\|string\|null\.$#'
+        - '#^Method ArchTech\\SEO\\SEOManager::flipp\(\) should return static\(ArchTech\\SEO\\SEOManager\)\|string but returns array\|string\|null\.$#'
diff --git a/src/SEOManager.php b/src/SEOManager.php
index d036034..d68a98f 100644
--- a/src/SEOManager.php
+++ b/src/SEOManager.php
@@ -82,11 +82,14 @@ class SEOManager
             : value($this->values[$key]);
     }

-    /** Set one or more values. */
+    /**
+     * Set one or more values.
+     *
+     * @param string|array<string, string> $key
+     */
     public function set(string|array $key, string|Closure|null $value = null): string|array|null
     {
         if (is_array($key)) {
-            /** @var array<string, string> $key */
             foreach ($key as $k => $v) {
                 $this->set($k, $v);
             }
@@ -166,7 +169,7 @@ class SEOManager
             ];
         }

-        $query = base64_encode(json_encode($data));
+        $query = base64_encode((string)json_encode($data));

         /** @var string $template */
         $template = $this->meta("flipp.templates.$alias");
@@ -273,7 +276,11 @@ class SEOManager
         return $this->get(Str::snake($key, '.'));
     }

-    /** Handle magic set. */
+    /**
+     * Handle magic set.
+     *
+     * @phpstan-return string|array|null
+     */
     public function __set(string $key, string $value)
     {
         return $this->set(Str::snake($key, '.'), $value);
diff --git a/src/helpers.php b/src/helpers.php
index 658df88..9a8e8f1 100644
--- a/src/helpers.php
+++ b/src/helpers.php
@@ -5,14 +5,21 @@ declare(strict_types=1);
 use ArchTech\SEO\SEOManager;

 if (! function_exists('seo')) {
+    /**
+     * @template T of string|array
+     * @param T|null $key
+     * @return SEOManager|string|array|null
+     */
     function seo(string|array $key = null): SEOManager|string|array|null
     {
-        if (! $key) {
+        if ($key === null) {
             return app('seo');
-        } elseif (is_array($key)) {
+        }
+
+        if (is_array($key)) {
             return app('seo')->set($key);
-        } else {
-            return app('seo')->get($key);
         }
+
+        return app('seo')->get($key);
     }
 }
```

It is 100% up to you! This is an inspiration, not code.

### PR DESCRIPTION
**Pull request by szepeviktor**
Closes #9

### CODE REVIEW

**Comment by szepeviktor** [comment]
The last one is _Expression on left side of ?? is not nullable._

https://github.com/archtechx/laravel-seo/blob/1b2bfb2945713f7c80cd0411fbbb27ec78c40b7f/src/SEOManager.php#L148

**Comment by stancl** [comment]
`meta()` returns a `$this|string` so null (usable by `??`) should never be returned

https://github.com/archtechx/laravel-seo/blob/1970b01773a4b29e3c6ffda6275bf566db0ff4ab/src/SEOManager.php#L218-L220

I assume the `null` can come from this call:
https://github.com/archtechx/laravel-seo/blob/1b2bfb2945713f7c80cd0411fbbb27ec78c40b7f/src/SEOManager.php#L229

So the return typehint should probably be updated to `$this|string|null`?

**Comment by stancl** [comment]
I've also just merged a PR into `master`. There are some new changes, can you make sure that this PR covers them? Probably just merge `master` into your branch.

**Comment by szepeviktor** [comment]
I am very happy to contribute.

File: src/SEOManager.php [hunk 1]
```diff
@@ -309,7 +312,11 @@ public function __get(string $key): string|null
         return $this->get(Str::snake($key, '.'));
     }
 
-    /** Handle magic set. */
+    /**
+     * Handle magic set.
+     *
+     * @phpstan-return string|array|null
```
Comment (stancl) [inline src/SEOManager.php:318]: Can we just use `@return` here? I'm generally trying to avoid any static analysis-specific annotations in code whenever possible. Ideal case scenario is only configuring things in the phpstan config file, and having the code agnostic of the static analysis.

File: src/helpers.php [hunk 2]
```diff
@@ -5,6 +5,10 @@
 use ArchTech\SEO\SEOManager;
 
 if (! function_exists('seo')) {
+    /**
+     * @template T of string|array
+     * @param T|null $key
```
Comment (stancl) [inline src/helpers.php:10]: What are these used for?

File: src/SEOManager.php (hunk 1 above)
Comment (szepeviktor) [reply src/SEOManager.php]: Done.

File: src/helpers.php (hunk 2 above)
Comment (szepeviktor) [reply src/helpers.php:10]: This is called PHP Generics.
https://phpstan.org/blog/generics-in-php-using-phpdocs
But I'm unable to cover all 3 types of calls on this method...

Comment (stancl) [reply src/helpers.php:10]: I know they're generics, I'm just wondering how they're used in specific here.

Comment (szepeviktor) [reply src/helpers.php:10]: I've started this PR with this: using generics in the `seo` function.
It has 3 functionalities. I've failed to write proper PHPDoc :(

Comment (stancl) [reply src/helpers.php:10]: We'll be merging one more PR and then I'll let you know the final feedback on this 👍🏻

**Comment by stancl** [comment]
okay, you can re-merge master now 👍🏻

File: src/helpers.php (hunk 2 above)
Comment (stancl) [reply src/helpers.php:10]: Okay, so should we keep the generics here? If it's not a full implementation then they should be removed.

Comment (szepeviktor) [reply src/helpers.php]: Done.

File: src/SEOManager.php [hunk 3]
```diff
@@ -166,7 +169,7 @@ public function flipp(string $alias, string|array $data = null): string|static
             ];
         }
 
-        $query = base64_encode(json_encode($data));
+        $query = base64_encode((string) json_encode($data));
```
Comment (stancl) [inline src/SEOManager.php:172]: What's the reason for the `(string)`, is it that `json_encode()` can return `false` on fail?

If so, you can pass a second argument with the flag to throw an exception. `JSON_THROW_ON_ERROR`

**Comment by stancl** [comment]
Final review probably

File: src/SEOManager.php (hunk 3 above)
Comment (szepeviktor) [reply src/SEOManager.php]: Done.

**Comment by stancl** [comment]
Thanks!
